// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Common/Cmd.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.Common {

  /// <summary>Holder for reflection information generated from Common/Cmd.proto</summary>
  public static partial class CmdReflection {

    #region Descriptor
    /// <summary>File descriptor for Common/Cmd.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CmdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBDb21tb24vQ21kLnByb3RvEgZDb21tb24idQoLQmFzZVNwaW5DbWQSEAoI",
            "VG90YWxCZXQYASABKAMSDwoHQnV5VHlwZRgCIAEoBRIQCghDdXJyZW5jeRgD",
            "IAEoCRISCgpBdXRvU3BpbklkGAQgASgJEg0KBVR1cmJvGAUgASgFEg4KBklz",
            "QXV0bxgGIAEoCCInCgdSVFBJbmZvEgsKA1JUUBgBIAEoBRIPCgdSVFBSYXRl",
            "GAIgASgNIooBCg5CYXNlU3BpblJlc3VsdBIMCgRDb2RlGAEgASgFEg8KB0J1",
            "eVR5cGUYAiABKAUSEAoIVG90YWxXaW4YAyABKAQSDwoHTWFpbldpbhgEIAEo",
            "BBIPCgdGcmVlV2luGAUgASgEEhMKC0ZHU3BpbkNvdW50GAYgASgFEhAKCEdh",
            "bWVNb2RlGAcgASgFQklaNWdpdGxhYi50aGUtZm9yY2UuY29tLnR3L3NlcnZl",
            "ci9wcm90b2J1Zi9HZW4vR28vQ29tbW9uqgIPUHJvdG9idWYuQ29tbW9uYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Common.BaseSpinCmd), global::Protobuf.Common.BaseSpinCmd.Parser, new[]{ "TotalBet", "BuyType", "Currency", "AutoSpinId", "Turbo", "IsAuto" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Common.RTPInfo), global::Protobuf.Common.RTPInfo.Parser, new[]{ "RTP", "RTPRate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Common.BaseSpinResult), global::Protobuf.Common.BaseSpinResult.Parser, new[]{ "Code", "BuyType", "TotalWin", "MainWin", "FreeWin", "FGSpinCount", "GameMode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BaseSpinCmd : pb::IMessage<BaseSpinCmd>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BaseSpinCmd> _parser = new pb::MessageParser<BaseSpinCmd>(() => new BaseSpinCmd());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BaseSpinCmd> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Common.CmdReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseSpinCmd() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseSpinCmd(BaseSpinCmd other) : this() {
      totalBet_ = other.totalBet_;
      buyType_ = other.buyType_;
      currency_ = other.currency_;
      autoSpinId_ = other.autoSpinId_;
      turbo_ = other.turbo_;
      isAuto_ = other.isAuto_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseSpinCmd Clone() {
      return new BaseSpinCmd(this);
    }

    /// <summary>Field number for the "TotalBet" field.</summary>
    public const int TotalBetFieldNumber = 1;
    private long totalBet_;
    /// <summary>
    /// 總投注額
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalBet {
      get { return totalBet_; }
      set {
        totalBet_ = value;
      }
    }

    /// <summary>Field number for the "BuyType" field.</summary>
    public const int BuyTypeFieldNumber = 2;
    private int buyType_;
    /// <summary>
    /// 購買類型 (0: 未買, 1: Buy ExtraBet, 2: Buy FreeSpins, 3: Buy SuperFreeSpins)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BuyType {
      get { return buyType_; }
      set {
        buyType_ = value;
      }
    }

    /// <summary>Field number for the "Currency" field.</summary>
    public const int CurrencyFieldNumber = 3;
    private string currency_ = "";
    /// <summary>
    /// 幣別
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Currency {
      get { return currency_; }
      set {
        currency_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AutoSpinId" field.</summary>
    public const int AutoSpinIdFieldNumber = 4;
    private string autoSpinId_ = "";
    /// <summary>
    /// 自動遊玩辨識ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AutoSpinId {
      get { return autoSpinId_; }
      set {
        autoSpinId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Turbo" field.</summary>
    public const int TurboFieldNumber = 5;
    private int turbo_;
    /// <summary>
    /// 加速
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Turbo {
      get { return turbo_; }
      set {
        turbo_ = value;
      }
    }

    /// <summary>Field number for the "IsAuto" field.</summary>
    public const int IsAutoFieldNumber = 6;
    private bool isAuto_;
    /// <summary>
    /// 自動
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsAuto {
      get { return isAuto_; }
      set {
        isAuto_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BaseSpinCmd);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BaseSpinCmd other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TotalBet != other.TotalBet) return false;
      if (BuyType != other.BuyType) return false;
      if (Currency != other.Currency) return false;
      if (AutoSpinId != other.AutoSpinId) return false;
      if (Turbo != other.Turbo) return false;
      if (IsAuto != other.IsAuto) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TotalBet != 0L) hash ^= TotalBet.GetHashCode();
      if (BuyType != 0) hash ^= BuyType.GetHashCode();
      if (Currency.Length != 0) hash ^= Currency.GetHashCode();
      if (AutoSpinId.Length != 0) hash ^= AutoSpinId.GetHashCode();
      if (Turbo != 0) hash ^= Turbo.GetHashCode();
      if (IsAuto != false) hash ^= IsAuto.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TotalBet != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TotalBet);
      }
      if (BuyType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(BuyType);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Currency);
      }
      if (AutoSpinId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AutoSpinId);
      }
      if (Turbo != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Turbo);
      }
      if (IsAuto != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsAuto);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TotalBet != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TotalBet);
      }
      if (BuyType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(BuyType);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Currency);
      }
      if (AutoSpinId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AutoSpinId);
      }
      if (Turbo != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Turbo);
      }
      if (IsAuto != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsAuto);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TotalBet != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalBet);
      }
      if (BuyType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuyType);
      }
      if (Currency.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Currency);
      }
      if (AutoSpinId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AutoSpinId);
      }
      if (Turbo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Turbo);
      }
      if (IsAuto != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BaseSpinCmd other) {
      if (other == null) {
        return;
      }
      if (other.TotalBet != 0L) {
        TotalBet = other.TotalBet;
      }
      if (other.BuyType != 0) {
        BuyType = other.BuyType;
      }
      if (other.Currency.Length != 0) {
        Currency = other.Currency;
      }
      if (other.AutoSpinId.Length != 0) {
        AutoSpinId = other.AutoSpinId;
      }
      if (other.Turbo != 0) {
        Turbo = other.Turbo;
      }
      if (other.IsAuto != false) {
        IsAuto = other.IsAuto;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TotalBet = input.ReadInt64();
            break;
          }
          case 16: {
            BuyType = input.ReadInt32();
            break;
          }
          case 26: {
            Currency = input.ReadString();
            break;
          }
          case 34: {
            AutoSpinId = input.ReadString();
            break;
          }
          case 40: {
            Turbo = input.ReadInt32();
            break;
          }
          case 48: {
            IsAuto = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TotalBet = input.ReadInt64();
            break;
          }
          case 16: {
            BuyType = input.ReadInt32();
            break;
          }
          case 26: {
            Currency = input.ReadString();
            break;
          }
          case 34: {
            AutoSpinId = input.ReadString();
            break;
          }
          case 40: {
            Turbo = input.ReadInt32();
            break;
          }
          case 48: {
            IsAuto = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RTPInfo : pb::IMessage<RTPInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RTPInfo> _parser = new pb::MessageParser<RTPInfo>(() => new RTPInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RTPInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Common.CmdReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RTPInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RTPInfo(RTPInfo other) : this() {
      rTP_ = other.rTP_;
      rTPRate_ = other.rTPRate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RTPInfo Clone() {
      return new RTPInfo(this);
    }

    /// <summary>Field number for the "RTP" field.</summary>
    public const int RTPFieldNumber = 1;
    private int rTP_;
    /// <summary>
    /// RTP 編號，由 gateway 提供
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RTP {
      get { return rTP_; }
      set {
        rTP_ = value;
      }
    }

    /// <summary>Field number for the "RTPRate" field.</summary>
    public const int RTPRateFieldNumber = 2;
    private uint rTPRate_;
    /// <summary>
    /// 目標 RTP 數值，由 gateway 提供(千分率‰)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RTPRate {
      get { return rTPRate_; }
      set {
        rTPRate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RTPInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RTPInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RTP != other.RTP) return false;
      if (RTPRate != other.RTPRate) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RTP != 0) hash ^= RTP.GetHashCode();
      if (RTPRate != 0) hash ^= RTPRate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RTP != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RTP);
      }
      if (RTPRate != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(RTPRate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RTP != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RTP);
      }
      if (RTPRate != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(RTPRate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RTP != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RTP);
      }
      if (RTPRate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RTPRate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RTPInfo other) {
      if (other == null) {
        return;
      }
      if (other.RTP != 0) {
        RTP = other.RTP;
      }
      if (other.RTPRate != 0) {
        RTPRate = other.RTPRate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RTP = input.ReadInt32();
            break;
          }
          case 16: {
            RTPRate = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RTP = input.ReadInt32();
            break;
          }
          case 16: {
            RTPRate = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BaseSpinResult : pb::IMessage<BaseSpinResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BaseSpinResult> _parser = new pb::MessageParser<BaseSpinResult>(() => new BaseSpinResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BaseSpinResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Common.CmdReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseSpinResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseSpinResult(BaseSpinResult other) : this() {
      code_ = other.code_;
      buyType_ = other.buyType_;
      totalWin_ = other.totalWin_;
      mainWin_ = other.mainWin_;
      freeWin_ = other.freeWin_;
      fGSpinCount_ = other.fGSpinCount_;
      gameMode_ = other.gameMode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseSpinResult Clone() {
      return new BaseSpinResult(this);
    }

    /// <summary>Field number for the "Code" field.</summary>
    public const int CodeFieldNumber = 1;
    private int code_;
    /// <summary>
    /// 回應代碼 (參考 ErrorCode.go)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "BuyType" field.</summary>
    public const int BuyTypeFieldNumber = 2;
    private int buyType_;
    /// <summary>
    /// 購買類型 (0: 未買, 1: Buy ExtraBet, 2: Buy FreeSpins, 3: Buy SuperFreeSpins)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BuyType {
      get { return buyType_; }
      set {
        buyType_ = value;
      }
    }

    /// <summary>Field number for the "TotalWin" field.</summary>
    public const int TotalWinFieldNumber = 3;
    private ulong totalWin_;
    /// <summary>
    /// 總贏分
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TotalWin {
      get { return totalWin_; }
      set {
        totalWin_ = value;
      }
    }

    /// <summary>Field number for the "MainWin" field.</summary>
    public const int MainWinFieldNumber = 4;
    private ulong mainWin_;
    /// <summary>
    /// 主遊戲贏分
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong MainWin {
      get { return mainWin_; }
      set {
        mainWin_ = value;
      }
    }

    /// <summary>Field number for the "FreeWin" field.</summary>
    public const int FreeWinFieldNumber = 5;
    private ulong freeWin_;
    /// <summary>
    /// 免費遊戲贏分
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong FreeWin {
      get { return freeWin_; }
      set {
        freeWin_ = value;
      }
    }

    /// <summary>Field number for the "FGSpinCount" field.</summary>
    public const int FGSpinCountFieldNumber = 6;
    private int fGSpinCount_;
    /// <summary>
    /// 免費遊戲 Spin 次數
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FGSpinCount {
      get { return fGSpinCount_; }
      set {
        fGSpinCount_ = value;
      }
    }

    /// <summary>Field number for the "GameMode" field.</summary>
    public const int GameModeFieldNumber = 7;
    private int gameMode_;
    /// <summary>
    /// 遊戲模式
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GameMode {
      get { return gameMode_; }
      set {
        gameMode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BaseSpinResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BaseSpinResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (BuyType != other.BuyType) return false;
      if (TotalWin != other.TotalWin) return false;
      if (MainWin != other.MainWin) return false;
      if (FreeWin != other.FreeWin) return false;
      if (FGSpinCount != other.FGSpinCount) return false;
      if (GameMode != other.GameMode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != 0) hash ^= Code.GetHashCode();
      if (BuyType != 0) hash ^= BuyType.GetHashCode();
      if (TotalWin != 0UL) hash ^= TotalWin.GetHashCode();
      if (MainWin != 0UL) hash ^= MainWin.GetHashCode();
      if (FreeWin != 0UL) hash ^= FreeWin.GetHashCode();
      if (FGSpinCount != 0) hash ^= FGSpinCount.GetHashCode();
      if (GameMode != 0) hash ^= GameMode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (BuyType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(BuyType);
      }
      if (TotalWin != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(TotalWin);
      }
      if (MainWin != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(MainWin);
      }
      if (FreeWin != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(FreeWin);
      }
      if (FGSpinCount != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(FGSpinCount);
      }
      if (GameMode != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(GameMode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (BuyType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(BuyType);
      }
      if (TotalWin != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(TotalWin);
      }
      if (MainWin != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(MainWin);
      }
      if (FreeWin != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(FreeWin);
      }
      if (FGSpinCount != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(FGSpinCount);
      }
      if (GameMode != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(GameMode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (BuyType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuyType);
      }
      if (TotalWin != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TotalWin);
      }
      if (MainWin != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MainWin);
      }
      if (FreeWin != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(FreeWin);
      }
      if (FGSpinCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FGSpinCount);
      }
      if (GameMode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameMode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BaseSpinResult other) {
      if (other == null) {
        return;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      if (other.BuyType != 0) {
        BuyType = other.BuyType;
      }
      if (other.TotalWin != 0UL) {
        TotalWin = other.TotalWin;
      }
      if (other.MainWin != 0UL) {
        MainWin = other.MainWin;
      }
      if (other.FreeWin != 0UL) {
        FreeWin = other.FreeWin;
      }
      if (other.FGSpinCount != 0) {
        FGSpinCount = other.FGSpinCount;
      }
      if (other.GameMode != 0) {
        GameMode = other.GameMode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 16: {
            BuyType = input.ReadInt32();
            break;
          }
          case 24: {
            TotalWin = input.ReadUInt64();
            break;
          }
          case 32: {
            MainWin = input.ReadUInt64();
            break;
          }
          case 40: {
            FreeWin = input.ReadUInt64();
            break;
          }
          case 48: {
            FGSpinCount = input.ReadInt32();
            break;
          }
          case 56: {
            GameMode = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 16: {
            BuyType = input.ReadInt32();
            break;
          }
          case 24: {
            TotalWin = input.ReadUInt64();
            break;
          }
          case 32: {
            MainWin = input.ReadUInt64();
            break;
          }
          case 40: {
            FreeWin = input.ReadUInt64();
            break;
          }
          case 48: {
            FGSpinCount = input.ReadInt32();
            break;
          }
          case 56: {
            GameMode = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
