// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameLog/GameLog.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.GameLog {

  /// <summary>Holder for reflection information generated from GameLog/GameLog.proto</summary>
  public static partial class GameLogReflection {

    #region Descriptor
    /// <summary>File descriptor for GameLog/GameLog.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameLogReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVHYW1lTG9nL0dhbWVMb2cucHJvdG8SB0dhbWVMb2caEENvbW1vbi9DbWQu",
            "cHJvdG8aGEdhdGV3YXkvTWVtYmVySW5mby5wcm90bxoYR2F0ZXdheS9EZXZp",
            "Y2VJbmZvLnByb3RvIowCCgpNc2dHYW1lTG9nEgsKA0NtZBgBIAEoCRIPCgdC",
            "YWxhbmNlGAIgASgEEiQKB1NwaW5DbWQYAyABKAsyEy5Db21tb24uQmFzZVNw",
            "aW5DbWQSKgoKU3BpblJlc3VsdBgEIAEoCzIWLkNvbW1vbi5CYXNlU3BpblJl",
            "c3VsdBIPCgdPcmRlcklEGAUgASgJEg8KB1JlcURhdGEYBiABKAwSEQoJUmVw",
            "bHlEYXRhGAcgASgMEg8KB1Byb2JWZXIYCCABKAkSIwoGTWVtYmVyGAkgASgL",
            "MhMuR2F0ZXdheS5NZW1iZXJJbmZvEiMKBkNsaWVudBgKIAEoCzITLkdhdGV3",
            "YXkuRGV2aWNlSW5mb0JTWj5naXRsYWIudGhlLWZvcmNlLmNvbS50dy9zZXJ2",
            "ZXIvcHJvdG9idWYvR2VuL0dvL0dhbWVMb2c7R2FtZUxvZ6oCEFByb3RvYnVm",
            "LkdhbWVMb2diBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protobuf.Common.CmdReflection.Descriptor, global::Protobuf.Gateway.MemberInfoReflection.Descriptor, global::Protobuf.Gateway.DeviceInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.GameLog.MsgGameLog), global::Protobuf.GameLog.MsgGameLog.Parser, new[]{ "Cmd", "Balance", "SpinCmd", "SpinResult", "OrderID", "ReqData", "ReplyData", "ProbVer", "Member", "Client" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// MsgGameLog Gateway To GameLog 的資料結構
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MsgGameLog : pb::IMessage<MsgGameLog>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgGameLog> _parser = new pb::MessageParser<MsgGameLog>(() => new MsgGameLog());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MsgGameLog> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.GameLog.GameLogReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgGameLog() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgGameLog(MsgGameLog other) : this() {
      cmd_ = other.cmd_;
      balance_ = other.balance_;
      spinCmd_ = other.spinCmd_ != null ? other.spinCmd_.Clone() : null;
      spinResult_ = other.spinResult_ != null ? other.spinResult_.Clone() : null;
      orderID_ = other.orderID_;
      reqData_ = other.reqData_;
      replyData_ = other.replyData_;
      probVer_ = other.probVer_;
      member_ = other.member_ != null ? other.member_.Clone() : null;
      client_ = other.client_ != null ? other.client_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgGameLog Clone() {
      return new MsgGameLog(this);
    }

    /// <summary>Field number for the "Cmd" field.</summary>
    public const int CmdFieldNumber = 1;
    private string cmd_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Cmd {
      get { return cmd_; }
      set {
        cmd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Balance" field.</summary>
    public const int BalanceFieldNumber = 2;
    private ulong balance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Balance {
      get { return balance_; }
      set {
        balance_ = value;
      }
    }

    /// <summary>Field number for the "SpinCmd" field.</summary>
    public const int SpinCmdFieldNumber = 3;
    private global::Protobuf.Common.BaseSpinCmd spinCmd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protobuf.Common.BaseSpinCmd SpinCmd {
      get { return spinCmd_; }
      set {
        spinCmd_ = value;
      }
    }

    /// <summary>Field number for the "SpinResult" field.</summary>
    public const int SpinResultFieldNumber = 4;
    private global::Protobuf.Common.BaseSpinResult spinResult_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protobuf.Common.BaseSpinResult SpinResult {
      get { return spinResult_; }
      set {
        spinResult_ = value;
      }
    }

    /// <summary>Field number for the "OrderID" field.</summary>
    public const int OrderIDFieldNumber = 5;
    private string orderID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OrderID {
      get { return orderID_; }
      set {
        orderID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ReqData" field.</summary>
    public const int ReqDataFieldNumber = 6;
    private pb::ByteString reqData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ReqData {
      get { return reqData_; }
      set {
        reqData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ReplyData" field.</summary>
    public const int ReplyDataFieldNumber = 7;
    private pb::ByteString replyData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ReplyData {
      get { return replyData_; }
      set {
        replyData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ProbVer" field.</summary>
    public const int ProbVerFieldNumber = 8;
    private string probVer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProbVer {
      get { return probVer_; }
      set {
        probVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Member" field.</summary>
    public const int MemberFieldNumber = 9;
    private global::Protobuf.Gateway.MemberInfo member_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protobuf.Gateway.MemberInfo Member {
      get { return member_; }
      set {
        member_ = value;
      }
    }

    /// <summary>Field number for the "Client" field.</summary>
    public const int ClientFieldNumber = 10;
    private global::Protobuf.Gateway.DeviceInfo client_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protobuf.Gateway.DeviceInfo Client {
      get { return client_; }
      set {
        client_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MsgGameLog);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MsgGameLog other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cmd != other.Cmd) return false;
      if (Balance != other.Balance) return false;
      if (!object.Equals(SpinCmd, other.SpinCmd)) return false;
      if (!object.Equals(SpinResult, other.SpinResult)) return false;
      if (OrderID != other.OrderID) return false;
      if (ReqData != other.ReqData) return false;
      if (ReplyData != other.ReplyData) return false;
      if (ProbVer != other.ProbVer) return false;
      if (!object.Equals(Member, other.Member)) return false;
      if (!object.Equals(Client, other.Client)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Cmd.Length != 0) hash ^= Cmd.GetHashCode();
      if (Balance != 0UL) hash ^= Balance.GetHashCode();
      if (spinCmd_ != null) hash ^= SpinCmd.GetHashCode();
      if (spinResult_ != null) hash ^= SpinResult.GetHashCode();
      if (OrderID.Length != 0) hash ^= OrderID.GetHashCode();
      if (ReqData.Length != 0) hash ^= ReqData.GetHashCode();
      if (ReplyData.Length != 0) hash ^= ReplyData.GetHashCode();
      if (ProbVer.Length != 0) hash ^= ProbVer.GetHashCode();
      if (member_ != null) hash ^= Member.GetHashCode();
      if (client_ != null) hash ^= Client.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Cmd.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Cmd);
      }
      if (Balance != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Balance);
      }
      if (spinCmd_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SpinCmd);
      }
      if (spinResult_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SpinResult);
      }
      if (OrderID.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(OrderID);
      }
      if (ReqData.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(ReqData);
      }
      if (ReplyData.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(ReplyData);
      }
      if (ProbVer.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ProbVer);
      }
      if (member_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Member);
      }
      if (client_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Client);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Cmd.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Cmd);
      }
      if (Balance != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Balance);
      }
      if (spinCmd_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SpinCmd);
      }
      if (spinResult_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SpinResult);
      }
      if (OrderID.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(OrderID);
      }
      if (ReqData.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(ReqData);
      }
      if (ReplyData.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(ReplyData);
      }
      if (ProbVer.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ProbVer);
      }
      if (member_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Member);
      }
      if (client_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Client);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Cmd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cmd);
      }
      if (Balance != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Balance);
      }
      if (spinCmd_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SpinCmd);
      }
      if (spinResult_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SpinResult);
      }
      if (OrderID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderID);
      }
      if (ReqData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ReqData);
      }
      if (ReplyData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ReplyData);
      }
      if (ProbVer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProbVer);
      }
      if (member_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Member);
      }
      if (client_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Client);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MsgGameLog other) {
      if (other == null) {
        return;
      }
      if (other.Cmd.Length != 0) {
        Cmd = other.Cmd;
      }
      if (other.Balance != 0UL) {
        Balance = other.Balance;
      }
      if (other.spinCmd_ != null) {
        if (spinCmd_ == null) {
          SpinCmd = new global::Protobuf.Common.BaseSpinCmd();
        }
        SpinCmd.MergeFrom(other.SpinCmd);
      }
      if (other.spinResult_ != null) {
        if (spinResult_ == null) {
          SpinResult = new global::Protobuf.Common.BaseSpinResult();
        }
        SpinResult.MergeFrom(other.SpinResult);
      }
      if (other.OrderID.Length != 0) {
        OrderID = other.OrderID;
      }
      if (other.ReqData.Length != 0) {
        ReqData = other.ReqData;
      }
      if (other.ReplyData.Length != 0) {
        ReplyData = other.ReplyData;
      }
      if (other.ProbVer.Length != 0) {
        ProbVer = other.ProbVer;
      }
      if (other.member_ != null) {
        if (member_ == null) {
          Member = new global::Protobuf.Gateway.MemberInfo();
        }
        Member.MergeFrom(other.Member);
      }
      if (other.client_ != null) {
        if (client_ == null) {
          Client = new global::Protobuf.Gateway.DeviceInfo();
        }
        Client.MergeFrom(other.Client);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Cmd = input.ReadString();
            break;
          }
          case 16: {
            Balance = input.ReadUInt64();
            break;
          }
          case 26: {
            if (spinCmd_ == null) {
              SpinCmd = new global::Protobuf.Common.BaseSpinCmd();
            }
            input.ReadMessage(SpinCmd);
            break;
          }
          case 34: {
            if (spinResult_ == null) {
              SpinResult = new global::Protobuf.Common.BaseSpinResult();
            }
            input.ReadMessage(SpinResult);
            break;
          }
          case 42: {
            OrderID = input.ReadString();
            break;
          }
          case 50: {
            ReqData = input.ReadBytes();
            break;
          }
          case 58: {
            ReplyData = input.ReadBytes();
            break;
          }
          case 66: {
            ProbVer = input.ReadString();
            break;
          }
          case 74: {
            if (member_ == null) {
              Member = new global::Protobuf.Gateway.MemberInfo();
            }
            input.ReadMessage(Member);
            break;
          }
          case 82: {
            if (client_ == null) {
              Client = new global::Protobuf.Gateway.DeviceInfo();
            }
            input.ReadMessage(Client);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Cmd = input.ReadString();
            break;
          }
          case 16: {
            Balance = input.ReadUInt64();
            break;
          }
          case 26: {
            if (spinCmd_ == null) {
              SpinCmd = new global::Protobuf.Common.BaseSpinCmd();
            }
            input.ReadMessage(SpinCmd);
            break;
          }
          case 34: {
            if (spinResult_ == null) {
              SpinResult = new global::Protobuf.Common.BaseSpinResult();
            }
            input.ReadMessage(SpinResult);
            break;
          }
          case 42: {
            OrderID = input.ReadString();
            break;
          }
          case 50: {
            ReqData = input.ReadBytes();
            break;
          }
          case 58: {
            ReplyData = input.ReadBytes();
            break;
          }
          case 66: {
            ProbVer = input.ReadString();
            break;
          }
          case 74: {
            if (member_ == null) {
              Member = new global::Protobuf.Gateway.MemberInfo();
            }
            input.ReadMessage(Member);
            break;
          }
          case 82: {
            if (client_ == null) {
              Client = new global::Protobuf.Gateway.DeviceInfo();
            }
            input.ReadMessage(Client);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
