// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Gateway/AutoSpin.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.Gateway {

  /// <summary>Holder for reflection information generated from Gateway/AutoSpin.proto</summary>
  public static partial class AutoSpinReflection {

    #region Descriptor
    /// <summary>File descriptor for Gateway/AutoSpin.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AutoSpinReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZHYXRld2F5L0F1dG9TcGluLnByb3RvEgdHYXRld2F5IowBCghBdXRvU3Bp",
            "bhISCgpBdXRvU3BpbklkGAEgASgJEhEKCVRvdGFsU3BpbhgCIAEoBRIRCglT",
            "dG9wUmF0aW8YAyABKAUSFwoPU3RvcExlc3NCYWxhbmNlGAQgASgBEhcKD1N0",
            "b3BNb3JlQmFsYW5jZRgFIAEoARIUCgxTdG9wRnJlZUdhbWUYBiABKAhCU1o+",
            "Z2l0bGFiLnRoZS1mb3JjZS5jb20udHcvc2VydmVyL3Byb3RvYnVmL0dlbi9H",
            "by9HYXRld2F5O0dhdGV3YXmqAhBQcm90b2J1Zi5HYXRld2F5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Gateway.AutoSpin), global::Protobuf.Gateway.AutoSpin.Parser, new[]{ "AutoSpinId", "TotalSpin", "StopRatio", "StopLessBalance", "StopMoreBalance", "StopFreeGame" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AutoSpin : pb::IMessage<AutoSpin>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AutoSpin> _parser = new pb::MessageParser<AutoSpin>(() => new AutoSpin());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AutoSpin> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Gateway.AutoSpinReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AutoSpin() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AutoSpin(AutoSpin other) : this() {
      autoSpinId_ = other.autoSpinId_;
      totalSpin_ = other.totalSpin_;
      stopRatio_ = other.stopRatio_;
      stopLessBalance_ = other.stopLessBalance_;
      stopMoreBalance_ = other.stopMoreBalance_;
      stopFreeGame_ = other.stopFreeGame_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AutoSpin Clone() {
      return new AutoSpin(this);
    }

    /// <summary>Field number for the "AutoSpinId" field.</summary>
    public const int AutoSpinIdFieldNumber = 1;
    private string autoSpinId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AutoSpinId {
      get { return autoSpinId_; }
      set {
        autoSpinId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TotalSpin" field.</summary>
    public const int TotalSpinFieldNumber = 2;
    private int totalSpin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TotalSpin {
      get { return totalSpin_; }
      set {
        totalSpin_ = value;
      }
    }

    /// <summary>Field number for the "StopRatio" field.</summary>
    public const int StopRatioFieldNumber = 3;
    private int stopRatio_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int StopRatio {
      get { return stopRatio_; }
      set {
        stopRatio_ = value;
      }
    }

    /// <summary>Field number for the "StopLessBalance" field.</summary>
    public const int StopLessBalanceFieldNumber = 4;
    private double stopLessBalance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double StopLessBalance {
      get { return stopLessBalance_; }
      set {
        stopLessBalance_ = value;
      }
    }

    /// <summary>Field number for the "StopMoreBalance" field.</summary>
    public const int StopMoreBalanceFieldNumber = 5;
    private double stopMoreBalance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double StopMoreBalance {
      get { return stopMoreBalance_; }
      set {
        stopMoreBalance_ = value;
      }
    }

    /// <summary>Field number for the "StopFreeGame" field.</summary>
    public const int StopFreeGameFieldNumber = 6;
    private bool stopFreeGame_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool StopFreeGame {
      get { return stopFreeGame_; }
      set {
        stopFreeGame_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AutoSpin);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AutoSpin other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AutoSpinId != other.AutoSpinId) return false;
      if (TotalSpin != other.TotalSpin) return false;
      if (StopRatio != other.StopRatio) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(StopLessBalance, other.StopLessBalance)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(StopMoreBalance, other.StopMoreBalance)) return false;
      if (StopFreeGame != other.StopFreeGame) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AutoSpinId.Length != 0) hash ^= AutoSpinId.GetHashCode();
      if (TotalSpin != 0) hash ^= TotalSpin.GetHashCode();
      if (StopRatio != 0) hash ^= StopRatio.GetHashCode();
      if (StopLessBalance != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(StopLessBalance);
      if (StopMoreBalance != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(StopMoreBalance);
      if (StopFreeGame != false) hash ^= StopFreeGame.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AutoSpinId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AutoSpinId);
      }
      if (TotalSpin != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TotalSpin);
      }
      if (StopRatio != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(StopRatio);
      }
      if (StopLessBalance != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(StopLessBalance);
      }
      if (StopMoreBalance != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(StopMoreBalance);
      }
      if (StopFreeGame != false) {
        output.WriteRawTag(48);
        output.WriteBool(StopFreeGame);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AutoSpinId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AutoSpinId);
      }
      if (TotalSpin != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TotalSpin);
      }
      if (StopRatio != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(StopRatio);
      }
      if (StopLessBalance != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(StopLessBalance);
      }
      if (StopMoreBalance != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(StopMoreBalance);
      }
      if (StopFreeGame != false) {
        output.WriteRawTag(48);
        output.WriteBool(StopFreeGame);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AutoSpinId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AutoSpinId);
      }
      if (TotalSpin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TotalSpin);
      }
      if (StopRatio != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StopRatio);
      }
      if (StopLessBalance != 0D) {
        size += 1 + 8;
      }
      if (StopMoreBalance != 0D) {
        size += 1 + 8;
      }
      if (StopFreeGame != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AutoSpin other) {
      if (other == null) {
        return;
      }
      if (other.AutoSpinId.Length != 0) {
        AutoSpinId = other.AutoSpinId;
      }
      if (other.TotalSpin != 0) {
        TotalSpin = other.TotalSpin;
      }
      if (other.StopRatio != 0) {
        StopRatio = other.StopRatio;
      }
      if (other.StopLessBalance != 0D) {
        StopLessBalance = other.StopLessBalance;
      }
      if (other.StopMoreBalance != 0D) {
        StopMoreBalance = other.StopMoreBalance;
      }
      if (other.StopFreeGame != false) {
        StopFreeGame = other.StopFreeGame;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AutoSpinId = input.ReadString();
            break;
          }
          case 16: {
            TotalSpin = input.ReadInt32();
            break;
          }
          case 24: {
            StopRatio = input.ReadInt32();
            break;
          }
          case 33: {
            StopLessBalance = input.ReadDouble();
            break;
          }
          case 41: {
            StopMoreBalance = input.ReadDouble();
            break;
          }
          case 48: {
            StopFreeGame = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AutoSpinId = input.ReadString();
            break;
          }
          case 16: {
            TotalSpin = input.ReadInt32();
            break;
          }
          case 24: {
            StopRatio = input.ReadInt32();
            break;
          }
          case 33: {
            StopLessBalance = input.ReadDouble();
            break;
          }
          case 41: {
            StopMoreBalance = input.ReadDouble();
            break;
          }
          case 48: {
            StopFreeGame = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
