// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Gateway/ClientClick.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.Gateway {

  /// <summary>Holder for reflection information generated from Gateway/ClientClick.proto</summary>
  public static partial class ClientClickReflection {

    #region Descriptor
    /// <summary>File descriptor for Gateway/ClientClick.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientClickReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlHYXRld2F5L0NsaWVudENsaWNrLnByb3RvEgdHYXRld2F5Gh9nb29nbGUv",
            "cHJvdG9idWYvdGltZXN0YW1wLnByb3RvIvsBCgtDbGllbnRDbGljaxINCgVD",
            "bGljaxgBIAEoBRIUCgxNYW51ZmFjdHVyZXIYAiABKAkSDQoFQnJhbmQYAyAB",
            "KAkSEgoKUmVzb2x1dGlvbhgEIAEoCRIPCgdOZXR3b3JrGAUgASgJEg8KB1N5",
            "c1R5cGUYBiABKAkSDgoGU3lzVmVyGAcgASgJEg8KB0Jyb3dzZXIYCCABKAkS",
            "EgoKQnJvd3NlclZlchgJIAEoCRILCgNWZXIYCiABKAkSEAoIRGV2aWNlSWQY",
            "CyABKAkSLgoKQ3JlYXRlVGltZRgMIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5U",
            "aW1lc3RhbXBCU1o+Z2l0bGFiLnRoZS1mb3JjZS5jb20udHcvc2VydmVyL3By",
            "b3RvYnVmL0dlbi9Hby9HYXRld2F5O0dhdGV3YXmqAhBQcm90b2J1Zi5HYXRl",
            "d2F5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Gateway.ClientClick), global::Protobuf.Gateway.ClientClick.Parser, new[]{ "Click", "Manufacturer", "Brand", "Resolution", "Network", "SysType", "SysVer", "Browser", "BrowserVer", "Ver", "DeviceId", "CreateTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClientClick : pb::IMessage<ClientClick>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClientClick> _parser = new pb::MessageParser<ClientClick>(() => new ClientClick());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClientClick> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Gateway.ClientClickReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientClick() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientClick(ClientClick other) : this() {
      click_ = other.click_;
      manufacturer_ = other.manufacturer_;
      brand_ = other.brand_;
      resolution_ = other.resolution_;
      network_ = other.network_;
      sysType_ = other.sysType_;
      sysVer_ = other.sysVer_;
      browser_ = other.browser_;
      browserVer_ = other.browserVer_;
      ver_ = other.ver_;
      deviceId_ = other.deviceId_;
      createTime_ = other.createTime_ != null ? other.createTime_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientClick Clone() {
      return new ClientClick(this);
    }

    /// <summary>Field number for the "Click" field.</summary>
    public const int ClickFieldNumber = 1;
    private int click_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Click {
      get { return click_; }
      set {
        click_ = value;
      }
    }

    /// <summary>Field number for the "Manufacturer" field.</summary>
    public const int ManufacturerFieldNumber = 2;
    private string manufacturer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Manufacturer {
      get { return manufacturer_; }
      set {
        manufacturer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Brand" field.</summary>
    public const int BrandFieldNumber = 3;
    private string brand_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Brand {
      get { return brand_; }
      set {
        brand_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Resolution" field.</summary>
    public const int ResolutionFieldNumber = 4;
    private string resolution_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Resolution {
      get { return resolution_; }
      set {
        resolution_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Network" field.</summary>
    public const int NetworkFieldNumber = 5;
    private string network_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Network {
      get { return network_; }
      set {
        network_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SysType" field.</summary>
    public const int SysTypeFieldNumber = 6;
    private string sysType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SysType {
      get { return sysType_; }
      set {
        sysType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SysVer" field.</summary>
    public const int SysVerFieldNumber = 7;
    private string sysVer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SysVer {
      get { return sysVer_; }
      set {
        sysVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Browser" field.</summary>
    public const int BrowserFieldNumber = 8;
    private string browser_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Browser {
      get { return browser_; }
      set {
        browser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "BrowserVer" field.</summary>
    public const int BrowserVerFieldNumber = 9;
    private string browserVer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BrowserVer {
      get { return browserVer_; }
      set {
        browserVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Ver" field.</summary>
    public const int VerFieldNumber = 10;
    private string ver_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ver {
      get { return ver_; }
      set {
        ver_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DeviceId" field.</summary>
    public const int DeviceIdFieldNumber = 11;
    private string deviceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeviceId {
      get { return deviceId_; }
      set {
        deviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CreateTime" field.</summary>
    public const int CreateTimeFieldNumber = 12;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreateTime {
      get { return createTime_; }
      set {
        createTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClientClick);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClientClick other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Click != other.Click) return false;
      if (Manufacturer != other.Manufacturer) return false;
      if (Brand != other.Brand) return false;
      if (Resolution != other.Resolution) return false;
      if (Network != other.Network) return false;
      if (SysType != other.SysType) return false;
      if (SysVer != other.SysVer) return false;
      if (Browser != other.Browser) return false;
      if (BrowserVer != other.BrowserVer) return false;
      if (Ver != other.Ver) return false;
      if (DeviceId != other.DeviceId) return false;
      if (!object.Equals(CreateTime, other.CreateTime)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Click != 0) hash ^= Click.GetHashCode();
      if (Manufacturer.Length != 0) hash ^= Manufacturer.GetHashCode();
      if (Brand.Length != 0) hash ^= Brand.GetHashCode();
      if (Resolution.Length != 0) hash ^= Resolution.GetHashCode();
      if (Network.Length != 0) hash ^= Network.GetHashCode();
      if (SysType.Length != 0) hash ^= SysType.GetHashCode();
      if (SysVer.Length != 0) hash ^= SysVer.GetHashCode();
      if (Browser.Length != 0) hash ^= Browser.GetHashCode();
      if (BrowserVer.Length != 0) hash ^= BrowserVer.GetHashCode();
      if (Ver.Length != 0) hash ^= Ver.GetHashCode();
      if (DeviceId.Length != 0) hash ^= DeviceId.GetHashCode();
      if (createTime_ != null) hash ^= CreateTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Click != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Click);
      }
      if (Manufacturer.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Manufacturer);
      }
      if (Brand.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Brand);
      }
      if (Resolution.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Resolution);
      }
      if (Network.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Network);
      }
      if (SysType.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SysType);
      }
      if (SysVer.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SysVer);
      }
      if (Browser.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Browser);
      }
      if (BrowserVer.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(BrowserVer);
      }
      if (Ver.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Ver);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(DeviceId);
      }
      if (createTime_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(CreateTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Click != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Click);
      }
      if (Manufacturer.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Manufacturer);
      }
      if (Brand.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Brand);
      }
      if (Resolution.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Resolution);
      }
      if (Network.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Network);
      }
      if (SysType.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SysType);
      }
      if (SysVer.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SysVer);
      }
      if (Browser.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Browser);
      }
      if (BrowserVer.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(BrowserVer);
      }
      if (Ver.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Ver);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(DeviceId);
      }
      if (createTime_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(CreateTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Click != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Click);
      }
      if (Manufacturer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Manufacturer);
      }
      if (Brand.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Brand);
      }
      if (Resolution.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Resolution);
      }
      if (Network.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Network);
      }
      if (SysType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SysType);
      }
      if (SysVer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SysVer);
      }
      if (Browser.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Browser);
      }
      if (BrowserVer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BrowserVer);
      }
      if (Ver.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ver);
      }
      if (DeviceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceId);
      }
      if (createTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreateTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClientClick other) {
      if (other == null) {
        return;
      }
      if (other.Click != 0) {
        Click = other.Click;
      }
      if (other.Manufacturer.Length != 0) {
        Manufacturer = other.Manufacturer;
      }
      if (other.Brand.Length != 0) {
        Brand = other.Brand;
      }
      if (other.Resolution.Length != 0) {
        Resolution = other.Resolution;
      }
      if (other.Network.Length != 0) {
        Network = other.Network;
      }
      if (other.SysType.Length != 0) {
        SysType = other.SysType;
      }
      if (other.SysVer.Length != 0) {
        SysVer = other.SysVer;
      }
      if (other.Browser.Length != 0) {
        Browser = other.Browser;
      }
      if (other.BrowserVer.Length != 0) {
        BrowserVer = other.BrowserVer;
      }
      if (other.Ver.Length != 0) {
        Ver = other.Ver;
      }
      if (other.DeviceId.Length != 0) {
        DeviceId = other.DeviceId;
      }
      if (other.createTime_ != null) {
        if (createTime_ == null) {
          CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreateTime.MergeFrom(other.CreateTime);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Click = input.ReadInt32();
            break;
          }
          case 18: {
            Manufacturer = input.ReadString();
            break;
          }
          case 26: {
            Brand = input.ReadString();
            break;
          }
          case 34: {
            Resolution = input.ReadString();
            break;
          }
          case 42: {
            Network = input.ReadString();
            break;
          }
          case 50: {
            SysType = input.ReadString();
            break;
          }
          case 58: {
            SysVer = input.ReadString();
            break;
          }
          case 66: {
            Browser = input.ReadString();
            break;
          }
          case 74: {
            BrowserVer = input.ReadString();
            break;
          }
          case 82: {
            Ver = input.ReadString();
            break;
          }
          case 90: {
            DeviceId = input.ReadString();
            break;
          }
          case 98: {
            if (createTime_ == null) {
              CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateTime);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Click = input.ReadInt32();
            break;
          }
          case 18: {
            Manufacturer = input.ReadString();
            break;
          }
          case 26: {
            Brand = input.ReadString();
            break;
          }
          case 34: {
            Resolution = input.ReadString();
            break;
          }
          case 42: {
            Network = input.ReadString();
            break;
          }
          case 50: {
            SysType = input.ReadString();
            break;
          }
          case 58: {
            SysVer = input.ReadString();
            break;
          }
          case 66: {
            Browser = input.ReadString();
            break;
          }
          case 74: {
            BrowserVer = input.ReadString();
            break;
          }
          case 82: {
            Ver = input.ReadString();
            break;
          }
          case 90: {
            DeviceId = input.ReadString();
            break;
          }
          case 98: {
            if (createTime_ == null) {
              CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateTime);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
