// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Gateway/Cmd.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.Gateway {

  /// <summary>Holder for reflection information generated from Gateway/Cmd.proto</summary>
  public static partial class CmdReflection {

    #region Descriptor
    /// <summary>File descriptor for Gateway/Cmd.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CmdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFHYXRld2F5L0NtZC5wcm90bxIHR2F0ZXdheRoQQ29tbW9uL0NtZC5wcm90",
            "bxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90byI5CglQYWNrZXRDbWQSCwoD",
            "Q21kGAEgASgJEhEKCVJlcXVlc3RJZBgCIAEoCRIMCgREYXRhGAMgASgMIo0B",
            "CgxSZXNwb25zZUluZm8SDAoEQ29kZRgBIAEoBRIPCgdNZXNzYWdlGAIgASgJ",
            "EgsKA0NtZBgDIAEoCRIRCglSZXF1ZXN0SWQYBCABKAkSDQoFVHhuSWQYBSAB",
            "KAkSDwoHQmFsYW5jZRgGIAEoBBIQCghDdXJyZW5jeRgHIAEoCRIMCgREYXRh",
            "GAggASgMImEKDUNsaWVudFNwaW5DbWQSKAoLQmFzZVNwaW5DbWQYASABKAsy",
            "Ey5Db21tb24uQmFzZVNwaW5DbWQSJgoIU3BpbkRhdGEYAiABKAsyFC5nb29n",
            "bGUucHJvdG9idWYuQW55In0KB1NwaW5DbWQSKAoLQmFzZVNwaW5DbWQYASAB",
            "KAsyEy5Db21tb24uQmFzZVNwaW5DbWQSIAoHUlRQSW5mbxgCIAEoCzIPLkNv",
            "bW1vbi5SVFBJbmZvEiYKCFNwaW5EYXRhGAMgASgLMhQuZ29vZ2xlLnByb3Rv",
            "YnVmLkFueSJmCgpTcGluUmVzdWx0Ei4KDkJhc2VTcGluUmVzdWx0GAEgASgL",
            "MhYuQ29tbW9uLkJhc2VTcGluUmVzdWx0EigKClNsb3RSZXN1bHQYAiABKAsy",
            "FC5nb29nbGUucHJvdG9idWYuQW55QlNaPmdpdGxhYi50aGUtZm9yY2UuY29t",
            "LnR3L3NlcnZlci9wcm90b2J1Zi9HZW4vR28vR2F0ZXdheTtHYXRld2F5qgIQ",
            "UHJvdG9idWYuR2F0ZXdheWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protobuf.Common.CmdReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Gateway.PacketCmd), global::Protobuf.Gateway.PacketCmd.Parser, new[]{ "Cmd", "RequestId", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Gateway.ResponseInfo), global::Protobuf.Gateway.ResponseInfo.Parser, new[]{ "Code", "Message", "Cmd", "RequestId", "TxnId", "Balance", "Currency", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Gateway.ClientSpinCmd), global::Protobuf.Gateway.ClientSpinCmd.Parser, new[]{ "BaseSpinCmd", "SpinData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Gateway.SpinCmd), global::Protobuf.Gateway.SpinCmd.Parser, new[]{ "BaseSpinCmd", "RTPInfo", "SpinData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Gateway.SpinResult), global::Protobuf.Gateway.SpinResult.Parser, new[]{ "BaseSpinResult", "SlotResult" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PacketCmd : pb::IMessage<PacketCmd>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PacketCmd> _parser = new pb::MessageParser<PacketCmd>(() => new PacketCmd());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PacketCmd> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Gateway.CmdReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PacketCmd() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PacketCmd(PacketCmd other) : this() {
      cmd_ = other.cmd_;
      requestId_ = other.requestId_;
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PacketCmd Clone() {
      return new PacketCmd(this);
    }

    /// <summary>Field number for the "Cmd" field.</summary>
    public const int CmdFieldNumber = 1;
    private string cmd_ = "";
    /// <summary>
    /// 命令種類
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Cmd {
      get { return cmd_; }
      set {
        cmd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "RequestId" field.</summary>
    public const int RequestIdFieldNumber = 2;
    private string requestId_ = "";
    /// <summary>
    /// 接收client每個命令id做回應區分
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 3;
    private pb::ByteString data_ = pb::ByteString.Empty;
    /// <summary>
    /// 封包資料
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PacketCmd);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PacketCmd other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cmd != other.Cmd) return false;
      if (RequestId != other.RequestId) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Cmd.Length != 0) hash ^= Cmd.GetHashCode();
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Cmd.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Cmd);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestId);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Cmd.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Cmd);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestId);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Cmd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cmd);
      }
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PacketCmd other) {
      if (other == null) {
        return;
      }
      if (other.Cmd.Length != 0) {
        Cmd = other.Cmd;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Cmd = input.ReadString();
            break;
          }
          case 18: {
            RequestId = input.ReadString();
            break;
          }
          case 26: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Cmd = input.ReadString();
            break;
          }
          case 18: {
            RequestId = input.ReadString();
            break;
          }
          case 26: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResponseInfo : pb::IMessage<ResponseInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResponseInfo> _parser = new pb::MessageParser<ResponseInfo>(() => new ResponseInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResponseInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Gateway.CmdReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseInfo(ResponseInfo other) : this() {
      code_ = other.code_;
      message_ = other.message_;
      cmd_ = other.cmd_;
      requestId_ = other.requestId_;
      txnId_ = other.txnId_;
      balance_ = other.balance_;
      currency_ = other.currency_;
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseInfo Clone() {
      return new ResponseInfo(this);
    }

    /// <summary>Field number for the "Code" field.</summary>
    public const int CodeFieldNumber = 1;
    private int code_;
    /// <summary>
    /// 回應的代碼
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    /// <summary>
    /// 回應的訊息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Cmd" field.</summary>
    public const int CmdFieldNumber = 3;
    private string cmd_ = "";
    /// <summary>
    /// 回應的命令種類
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Cmd {
      get { return cmd_; }
      set {
        cmd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "RequestId" field.</summary>
    public const int RequestIdFieldNumber = 4;
    private string requestId_ = "";
    /// <summary>
    /// 接收client每個命令id做回應區分
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TxnId" field.</summary>
    public const int TxnIdFieldNumber = 5;
    private string txnId_ = "";
    /// <summary>
    /// 若投注成功回傳單號
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TxnId {
      get { return txnId_; }
      set {
        txnId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Balance" field.</summary>
    public const int BalanceFieldNumber = 6;
    private ulong balance_;
    /// <summary>
    /// spin後餘額
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Balance {
      get { return balance_; }
      set {
        balance_ = value;
      }
    }

    /// <summary>Field number for the "Currency" field.</summary>
    public const int CurrencyFieldNumber = 7;
    private string currency_ = "";
    /// <summary>
    /// 幣別
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Currency {
      get { return currency_; }
      set {
        currency_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 8;
    private pb::ByteString data_ = pb::ByteString.Empty;
    /// <summary>
    /// 回應的資料
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResponseInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResponseInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Message != other.Message) return false;
      if (Cmd != other.Cmd) return false;
      if (RequestId != other.RequestId) return false;
      if (TxnId != other.TxnId) return false;
      if (Balance != other.Balance) return false;
      if (Currency != other.Currency) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != 0) hash ^= Code.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Cmd.Length != 0) hash ^= Cmd.GetHashCode();
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (TxnId.Length != 0) hash ^= TxnId.GetHashCode();
      if (Balance != 0UL) hash ^= Balance.GetHashCode();
      if (Currency.Length != 0) hash ^= Currency.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Cmd.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Cmd);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(RequestId);
      }
      if (TxnId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TxnId);
      }
      if (Balance != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(Balance);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Currency);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(66);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Cmd.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Cmd);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(RequestId);
      }
      if (TxnId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TxnId);
      }
      if (Balance != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(Balance);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Currency);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(66);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Cmd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cmd);
      }
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (TxnId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TxnId);
      }
      if (Balance != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Balance);
      }
      if (Currency.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Currency);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResponseInfo other) {
      if (other == null) {
        return;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Cmd.Length != 0) {
        Cmd = other.Cmd;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.TxnId.Length != 0) {
        TxnId = other.TxnId;
      }
      if (other.Balance != 0UL) {
        Balance = other.Balance;
      }
      if (other.Currency.Length != 0) {
        Currency = other.Currency;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 26: {
            Cmd = input.ReadString();
            break;
          }
          case 34: {
            RequestId = input.ReadString();
            break;
          }
          case 42: {
            TxnId = input.ReadString();
            break;
          }
          case 48: {
            Balance = input.ReadUInt64();
            break;
          }
          case 58: {
            Currency = input.ReadString();
            break;
          }
          case 66: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 26: {
            Cmd = input.ReadString();
            break;
          }
          case 34: {
            RequestId = input.ReadString();
            break;
          }
          case 42: {
            TxnId = input.ReadString();
            break;
          }
          case 48: {
            Balance = input.ReadUInt64();
            break;
          }
          case 58: {
            Currency = input.ReadString();
            break;
          }
          case 66: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ClientSpinCmd Client To Gateway 資料結構
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClientSpinCmd : pb::IMessage<ClientSpinCmd>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClientSpinCmd> _parser = new pb::MessageParser<ClientSpinCmd>(() => new ClientSpinCmd());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClientSpinCmd> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Gateway.CmdReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientSpinCmd() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientSpinCmd(ClientSpinCmd other) : this() {
      baseSpinCmd_ = other.baseSpinCmd_ != null ? other.baseSpinCmd_.Clone() : null;
      spinData_ = other.spinData_ != null ? other.spinData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientSpinCmd Clone() {
      return new ClientSpinCmd(this);
    }

    /// <summary>Field number for the "BaseSpinCmd" field.</summary>
    public const int BaseSpinCmdFieldNumber = 1;
    private global::Protobuf.Common.BaseSpinCmd baseSpinCmd_;
    /// <summary>
    /// Client 轉給 Gateway 接收的資訊
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protobuf.Common.BaseSpinCmd BaseSpinCmd {
      get { return baseSpinCmd_; }
      set {
        baseSpinCmd_ = value;
      }
    }

    /// <summary>Field number for the "SpinData" field.</summary>
    public const int SpinDataFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Any spinData_;
    /// <summary>
    /// 存放要轉發給 GameService 而 Gateway 不需解析的 SpinCmd(Proto) 資訊
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any SpinData {
      get { return spinData_; }
      set {
        spinData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClientSpinCmd);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClientSpinCmd other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BaseSpinCmd, other.BaseSpinCmd)) return false;
      if (!object.Equals(SpinData, other.SpinData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (baseSpinCmd_ != null) hash ^= BaseSpinCmd.GetHashCode();
      if (spinData_ != null) hash ^= SpinData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (baseSpinCmd_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BaseSpinCmd);
      }
      if (spinData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SpinData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (baseSpinCmd_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BaseSpinCmd);
      }
      if (spinData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SpinData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (baseSpinCmd_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BaseSpinCmd);
      }
      if (spinData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SpinData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClientSpinCmd other) {
      if (other == null) {
        return;
      }
      if (other.baseSpinCmd_ != null) {
        if (baseSpinCmd_ == null) {
          BaseSpinCmd = new global::Protobuf.Common.BaseSpinCmd();
        }
        BaseSpinCmd.MergeFrom(other.BaseSpinCmd);
      }
      if (other.spinData_ != null) {
        if (spinData_ == null) {
          SpinData = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        SpinData.MergeFrom(other.SpinData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (baseSpinCmd_ == null) {
              BaseSpinCmd = new global::Protobuf.Common.BaseSpinCmd();
            }
            input.ReadMessage(BaseSpinCmd);
            break;
          }
          case 18: {
            if (spinData_ == null) {
              SpinData = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(SpinData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (baseSpinCmd_ == null) {
              BaseSpinCmd = new global::Protobuf.Common.BaseSpinCmd();
            }
            input.ReadMessage(BaseSpinCmd);
            break;
          }
          case 18: {
            if (spinData_ == null) {
              SpinData = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(SpinData);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// SpinCmd Gateway To GameService 資料結構
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SpinCmd : pb::IMessage<SpinCmd>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SpinCmd> _parser = new pb::MessageParser<SpinCmd>(() => new SpinCmd());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SpinCmd> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Gateway.CmdReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpinCmd() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpinCmd(SpinCmd other) : this() {
      baseSpinCmd_ = other.baseSpinCmd_ != null ? other.baseSpinCmd_.Clone() : null;
      rTPInfo_ = other.rTPInfo_ != null ? other.rTPInfo_.Clone() : null;
      spinData_ = other.spinData_ != null ? other.spinData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpinCmd Clone() {
      return new SpinCmd(this);
    }

    /// <summary>Field number for the "BaseSpinCmd" field.</summary>
    public const int BaseSpinCmdFieldNumber = 1;
    private global::Protobuf.Common.BaseSpinCmd baseSpinCmd_;
    /// <summary>
    /// Client 轉給 Gateway 接收的資訊
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protobuf.Common.BaseSpinCmd BaseSpinCmd {
      get { return baseSpinCmd_; }
      set {
        baseSpinCmd_ = value;
      }
    }

    /// <summary>Field number for the "RTPInfo" field.</summary>
    public const int RTPInfoFieldNumber = 2;
    private global::Protobuf.Common.RTPInfo rTPInfo_;
    /// <summary>
    /// RTP 資訊，由 gateway 提供
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protobuf.Common.RTPInfo RTPInfo {
      get { return rTPInfo_; }
      set {
        rTPInfo_ = value;
      }
    }

    /// <summary>Field number for the "SpinData" field.</summary>
    public const int SpinDataFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Any spinData_;
    /// <summary>
    /// 存放要轉發給 GameService 而 Gateway 不需解析的 SpinCmd(Proto) 資料
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any SpinData {
      get { return spinData_; }
      set {
        spinData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SpinCmd);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SpinCmd other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BaseSpinCmd, other.BaseSpinCmd)) return false;
      if (!object.Equals(RTPInfo, other.RTPInfo)) return false;
      if (!object.Equals(SpinData, other.SpinData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (baseSpinCmd_ != null) hash ^= BaseSpinCmd.GetHashCode();
      if (rTPInfo_ != null) hash ^= RTPInfo.GetHashCode();
      if (spinData_ != null) hash ^= SpinData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (baseSpinCmd_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BaseSpinCmd);
      }
      if (rTPInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RTPInfo);
      }
      if (spinData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SpinData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (baseSpinCmd_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BaseSpinCmd);
      }
      if (rTPInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RTPInfo);
      }
      if (spinData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SpinData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (baseSpinCmd_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BaseSpinCmd);
      }
      if (rTPInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RTPInfo);
      }
      if (spinData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SpinData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SpinCmd other) {
      if (other == null) {
        return;
      }
      if (other.baseSpinCmd_ != null) {
        if (baseSpinCmd_ == null) {
          BaseSpinCmd = new global::Protobuf.Common.BaseSpinCmd();
        }
        BaseSpinCmd.MergeFrom(other.BaseSpinCmd);
      }
      if (other.rTPInfo_ != null) {
        if (rTPInfo_ == null) {
          RTPInfo = new global::Protobuf.Common.RTPInfo();
        }
        RTPInfo.MergeFrom(other.RTPInfo);
      }
      if (other.spinData_ != null) {
        if (spinData_ == null) {
          SpinData = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        SpinData.MergeFrom(other.SpinData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (baseSpinCmd_ == null) {
              BaseSpinCmd = new global::Protobuf.Common.BaseSpinCmd();
            }
            input.ReadMessage(BaseSpinCmd);
            break;
          }
          case 18: {
            if (rTPInfo_ == null) {
              RTPInfo = new global::Protobuf.Common.RTPInfo();
            }
            input.ReadMessage(RTPInfo);
            break;
          }
          case 26: {
            if (spinData_ == null) {
              SpinData = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(SpinData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (baseSpinCmd_ == null) {
              BaseSpinCmd = new global::Protobuf.Common.BaseSpinCmd();
            }
            input.ReadMessage(BaseSpinCmd);
            break;
          }
          case 18: {
            if (rTPInfo_ == null) {
              RTPInfo = new global::Protobuf.Common.RTPInfo();
            }
            input.ReadMessage(RTPInfo);
            break;
          }
          case 26: {
            if (spinData_ == null) {
              SpinData = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(SpinData);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// SpinCmd GameService To Gateway 資料結構
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SpinResult : pb::IMessage<SpinResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SpinResult> _parser = new pb::MessageParser<SpinResult>(() => new SpinResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SpinResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Gateway.CmdReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpinResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpinResult(SpinResult other) : this() {
      baseSpinResult_ = other.baseSpinResult_ != null ? other.baseSpinResult_.Clone() : null;
      slotResult_ = other.slotResult_ != null ? other.slotResult_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpinResult Clone() {
      return new SpinResult(this);
    }

    /// <summary>Field number for the "BaseSpinResult" field.</summary>
    public const int BaseSpinResultFieldNumber = 1;
    private global::Protobuf.Common.BaseSpinResult baseSpinResult_;
    /// <summary>
    /// GameServcie 轉給 Gateway 接收的資訊
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protobuf.Common.BaseSpinResult BaseSpinResult {
      get { return baseSpinResult_; }
      set {
        baseSpinResult_ = value;
      }
    }

    /// <summary>Field number for the "SlotResult" field.</summary>
    public const int SlotResultFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Any slotResult_;
    /// <summary>
    /// 存放要轉發給 Client 而 Gateway 不需解析的 SlotResult(Proto) 資料
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any SlotResult {
      get { return slotResult_; }
      set {
        slotResult_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SpinResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SpinResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BaseSpinResult, other.BaseSpinResult)) return false;
      if (!object.Equals(SlotResult, other.SlotResult)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (baseSpinResult_ != null) hash ^= BaseSpinResult.GetHashCode();
      if (slotResult_ != null) hash ^= SlotResult.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (baseSpinResult_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BaseSpinResult);
      }
      if (slotResult_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SlotResult);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (baseSpinResult_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BaseSpinResult);
      }
      if (slotResult_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SlotResult);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (baseSpinResult_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BaseSpinResult);
      }
      if (slotResult_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SlotResult);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SpinResult other) {
      if (other == null) {
        return;
      }
      if (other.baseSpinResult_ != null) {
        if (baseSpinResult_ == null) {
          BaseSpinResult = new global::Protobuf.Common.BaseSpinResult();
        }
        BaseSpinResult.MergeFrom(other.BaseSpinResult);
      }
      if (other.slotResult_ != null) {
        if (slotResult_ == null) {
          SlotResult = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        SlotResult.MergeFrom(other.SlotResult);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (baseSpinResult_ == null) {
              BaseSpinResult = new global::Protobuf.Common.BaseSpinResult();
            }
            input.ReadMessage(BaseSpinResult);
            break;
          }
          case 18: {
            if (slotResult_ == null) {
              SlotResult = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(SlotResult);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (baseSpinResult_ == null) {
              BaseSpinResult = new global::Protobuf.Common.BaseSpinResult();
            }
            input.ReadMessage(BaseSpinResult);
            break;
          }
          case 18: {
            if (slotResult_ == null) {
              SlotResult = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(SlotResult);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
