// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Gateway/DeviceInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.Gateway {

  /// <summary>Holder for reflection information generated from Gateway/DeviceInfo.proto</summary>
  public static partial class DeviceInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for Gateway/DeviceInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DeviceInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhHYXRld2F5L0RldmljZUluZm8ucHJvdG8SB0dhdGV3YXkiuwEKCkRldmlj",
            "ZUluZm8SFAoMTWFudWZhY3R1cmVyGAEgASgJEg0KBUJyYW5kGAIgASgJEhIK",
            "ClJlc29sdXRpb24YAyABKAkSDwoHTmV0d29yaxgEIAEoCRIPCgdTeXNUeXBl",
            "GAUgASgJEg4KBlN5c1ZlchgGIAEoCRIPCgdCcm93c2VyGAcgASgJEhIKCkJy",
            "b3dzZXJWZXIYCCABKAkSEAoIRGV2aWNlSWQYCSABKAkSCwoDVmVyGAogASgJ",
            "QlNaPmdpdGxhYi50aGUtZm9yY2UuY29tLnR3L3NlcnZlci9wcm90b2J1Zi9H",
            "ZW4vR28vR2F0ZXdheTtHYXRld2F5qgIQUHJvdG9idWYuR2F0ZXdheWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Gateway.DeviceInfo), global::Protobuf.Gateway.DeviceInfo.Parser, new[]{ "Manufacturer", "Brand", "Resolution", "Network", "SysType", "SysVer", "Browser", "BrowserVer", "DeviceId", "Ver" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// DeviceInfo Common.CMD_DEVICE_INFO 遊戲client傳送裝置資訊, 供數據組使用
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DeviceInfo : pb::IMessage<DeviceInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeviceInfo> _parser = new pb::MessageParser<DeviceInfo>(() => new DeviceInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DeviceInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Gateway.DeviceInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceInfo(DeviceInfo other) : this() {
      manufacturer_ = other.manufacturer_;
      brand_ = other.brand_;
      resolution_ = other.resolution_;
      network_ = other.network_;
      sysType_ = other.sysType_;
      sysVer_ = other.sysVer_;
      browser_ = other.browser_;
      browserVer_ = other.browserVer_;
      deviceId_ = other.deviceId_;
      ver_ = other.ver_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceInfo Clone() {
      return new DeviceInfo(this);
    }

    /// <summary>Field number for the "Manufacturer" field.</summary>
    public const int ManufacturerFieldNumber = 1;
    private string manufacturer_ = "";
    /// <summary>
    /// 裝置製造商
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Manufacturer {
      get { return manufacturer_; }
      set {
        manufacturer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Brand" field.</summary>
    public const int BrandFieldNumber = 2;
    private string brand_ = "";
    /// <summary>
    /// 裝置型號
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Brand {
      get { return brand_; }
      set {
        brand_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Resolution" field.</summary>
    public const int ResolutionFieldNumber = 3;
    private string resolution_ = "";
    /// <summary>
    /// 裝置解析度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Resolution {
      get { return resolution_; }
      set {
        resolution_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Network" field.</summary>
    public const int NetworkFieldNumber = 4;
    private string network_ = "";
    /// <summary>
    /// 網路類型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Network {
      get { return network_; }
      set {
        network_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SysType" field.</summary>
    public const int SysTypeFieldNumber = 5;
    private string sysType_ = "";
    /// <summary>
    /// 作業系統
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SysType {
      get { return sysType_; }
      set {
        sysType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SysVer" field.</summary>
    public const int SysVerFieldNumber = 6;
    private string sysVer_ = "";
    /// <summary>
    /// 作業系統版本
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SysVer {
      get { return sysVer_; }
      set {
        sysVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Browser" field.</summary>
    public const int BrowserFieldNumber = 7;
    private string browser_ = "";
    /// <summary>
    /// 瀏覽器
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Browser {
      get { return browser_; }
      set {
        browser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "BrowserVer" field.</summary>
    public const int BrowserVerFieldNumber = 8;
    private string browserVer_ = "";
    /// <summary>
    /// 瀏覽器版本
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BrowserVer {
      get { return browserVer_; }
      set {
        browserVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DeviceId" field.</summary>
    public const int DeviceIdFieldNumber = 9;
    private string deviceId_ = "";
    /// <summary>
    /// 裝置ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeviceId {
      get { return deviceId_; }
      set {
        deviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Ver" field.</summary>
    public const int VerFieldNumber = 10;
    private string ver_ = "";
    /// <summary>
    /// Client版號
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ver {
      get { return ver_; }
      set {
        ver_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DeviceInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DeviceInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Manufacturer != other.Manufacturer) return false;
      if (Brand != other.Brand) return false;
      if (Resolution != other.Resolution) return false;
      if (Network != other.Network) return false;
      if (SysType != other.SysType) return false;
      if (SysVer != other.SysVer) return false;
      if (Browser != other.Browser) return false;
      if (BrowserVer != other.BrowserVer) return false;
      if (DeviceId != other.DeviceId) return false;
      if (Ver != other.Ver) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Manufacturer.Length != 0) hash ^= Manufacturer.GetHashCode();
      if (Brand.Length != 0) hash ^= Brand.GetHashCode();
      if (Resolution.Length != 0) hash ^= Resolution.GetHashCode();
      if (Network.Length != 0) hash ^= Network.GetHashCode();
      if (SysType.Length != 0) hash ^= SysType.GetHashCode();
      if (SysVer.Length != 0) hash ^= SysVer.GetHashCode();
      if (Browser.Length != 0) hash ^= Browser.GetHashCode();
      if (BrowserVer.Length != 0) hash ^= BrowserVer.GetHashCode();
      if (DeviceId.Length != 0) hash ^= DeviceId.GetHashCode();
      if (Ver.Length != 0) hash ^= Ver.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Manufacturer.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Manufacturer);
      }
      if (Brand.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Brand);
      }
      if (Resolution.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Resolution);
      }
      if (Network.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Network);
      }
      if (SysType.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SysType);
      }
      if (SysVer.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SysVer);
      }
      if (Browser.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Browser);
      }
      if (BrowserVer.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(BrowserVer);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(DeviceId);
      }
      if (Ver.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Ver);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Manufacturer.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Manufacturer);
      }
      if (Brand.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Brand);
      }
      if (Resolution.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Resolution);
      }
      if (Network.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Network);
      }
      if (SysType.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SysType);
      }
      if (SysVer.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SysVer);
      }
      if (Browser.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Browser);
      }
      if (BrowserVer.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(BrowserVer);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(DeviceId);
      }
      if (Ver.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Ver);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Manufacturer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Manufacturer);
      }
      if (Brand.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Brand);
      }
      if (Resolution.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Resolution);
      }
      if (Network.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Network);
      }
      if (SysType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SysType);
      }
      if (SysVer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SysVer);
      }
      if (Browser.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Browser);
      }
      if (BrowserVer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BrowserVer);
      }
      if (DeviceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceId);
      }
      if (Ver.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ver);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DeviceInfo other) {
      if (other == null) {
        return;
      }
      if (other.Manufacturer.Length != 0) {
        Manufacturer = other.Manufacturer;
      }
      if (other.Brand.Length != 0) {
        Brand = other.Brand;
      }
      if (other.Resolution.Length != 0) {
        Resolution = other.Resolution;
      }
      if (other.Network.Length != 0) {
        Network = other.Network;
      }
      if (other.SysType.Length != 0) {
        SysType = other.SysType;
      }
      if (other.SysVer.Length != 0) {
        SysVer = other.SysVer;
      }
      if (other.Browser.Length != 0) {
        Browser = other.Browser;
      }
      if (other.BrowserVer.Length != 0) {
        BrowserVer = other.BrowserVer;
      }
      if (other.DeviceId.Length != 0) {
        DeviceId = other.DeviceId;
      }
      if (other.Ver.Length != 0) {
        Ver = other.Ver;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Manufacturer = input.ReadString();
            break;
          }
          case 18: {
            Brand = input.ReadString();
            break;
          }
          case 26: {
            Resolution = input.ReadString();
            break;
          }
          case 34: {
            Network = input.ReadString();
            break;
          }
          case 42: {
            SysType = input.ReadString();
            break;
          }
          case 50: {
            SysVer = input.ReadString();
            break;
          }
          case 58: {
            Browser = input.ReadString();
            break;
          }
          case 66: {
            BrowserVer = input.ReadString();
            break;
          }
          case 74: {
            DeviceId = input.ReadString();
            break;
          }
          case 82: {
            Ver = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Manufacturer = input.ReadString();
            break;
          }
          case 18: {
            Brand = input.ReadString();
            break;
          }
          case 26: {
            Resolution = input.ReadString();
            break;
          }
          case 34: {
            Network = input.ReadString();
            break;
          }
          case 42: {
            SysType = input.ReadString();
            break;
          }
          case 50: {
            SysVer = input.ReadString();
            break;
          }
          case 58: {
            Browser = input.ReadString();
            break;
          }
          case 66: {
            BrowserVer = input.ReadString();
            break;
          }
          case 74: {
            DeviceId = input.ReadString();
            break;
          }
          case 82: {
            Ver = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
