// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Gateway/GameInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.Gateway {

  /// <summary>Holder for reflection information generated from Gateway/GameInfo.proto</summary>
  public static partial class GameInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for Gateway/GameInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZHYXRld2F5L0dhbWVJbmZvLnByb3RvEgdHYXRld2F5IjQKDkdldEdhbWVJ",
            "bmZvQ21kEhAKCEdhbWVOYW1lGAEgASgJEhAKCEN1cnJlbmN5GAIgASgJIpEB",
            "Cg9SZXNwR2V0R2FtZUluZm8SDgoGR2FtZUlEGAEgASgFEhAKCEdhbWVDb2Rl",
            "GAIgASgJEhAKCEdhbWVUeXBlGAMgASgJEhEKCVJlY29yZFVybBgEIAEoCRIQ",
            "CghCZXRSYW5nZRgFIAMoBBIOCgZNYXhXaW4YByABKAUSFQoNQ2xpZW50T3B0",
            "aW9ucxgGIAEoCUJTWj5naXRsYWIudGhlLWZvcmNlLmNvbS50dy9zZXJ2ZXIv",
            "cHJvdG9idWYvR2VuL0dvL0dhdGV3YXk7R2F0ZXdheaoCEFByb3RvYnVmLkdh",
            "dGV3YXliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Gateway.GetGameInfoCmd), global::Protobuf.Gateway.GetGameInfoCmd.Parser, new[]{ "GameName", "Currency" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Gateway.RespGetGameInfo), global::Protobuf.Gateway.RespGetGameInfo.Parser, new[]{ "GameID", "GameCode", "GameType", "RecordUrl", "BetRange", "MaxWin", "ClientOptions" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// GetGameInfoCmd Common.CMD_GET_GAMEINFO
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetGameInfoCmd : pb::IMessage<GetGameInfoCmd>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetGameInfoCmd> _parser = new pb::MessageParser<GetGameInfoCmd>(() => new GetGameInfoCmd());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetGameInfoCmd> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Gateway.GameInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetGameInfoCmd() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetGameInfoCmd(GetGameInfoCmd other) : this() {
      gameName_ = other.gameName_;
      currency_ = other.currency_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetGameInfoCmd Clone() {
      return new GetGameInfoCmd(this);
    }

    /// <summary>Field number for the "GameName" field.</summary>
    public const int GameNameFieldNumber = 1;
    private string gameName_ = "";
    /// <summary>
    /// 遊戲名稱
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GameName {
      get { return gameName_; }
      set {
        gameName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Currency" field.</summary>
    public const int CurrencyFieldNumber = 2;
    private string currency_ = "";
    /// <summary>
    /// 幣別
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Currency {
      get { return currency_; }
      set {
        currency_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetGameInfoCmd);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetGameInfoCmd other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameName != other.GameName) return false;
      if (Currency != other.Currency) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GameName.Length != 0) hash ^= GameName.GetHashCode();
      if (Currency.Length != 0) hash ^= Currency.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GameName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(GameName);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Currency);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GameName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(GameName);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Currency);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GameName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameName);
      }
      if (Currency.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Currency);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetGameInfoCmd other) {
      if (other == null) {
        return;
      }
      if (other.GameName.Length != 0) {
        GameName = other.GameName;
      }
      if (other.Currency.Length != 0) {
        Currency = other.Currency;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            GameName = input.ReadString();
            break;
          }
          case 18: {
            Currency = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            GameName = input.ReadString();
            break;
          }
          case 18: {
            Currency = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RespGetGameInfo : pb::IMessage<RespGetGameInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RespGetGameInfo> _parser = new pb::MessageParser<RespGetGameInfo>(() => new RespGetGameInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RespGetGameInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Gateway.GameInfoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespGetGameInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespGetGameInfo(RespGetGameInfo other) : this() {
      gameID_ = other.gameID_;
      gameCode_ = other.gameCode_;
      gameType_ = other.gameType_;
      recordUrl_ = other.recordUrl_;
      betRange_ = other.betRange_.Clone();
      maxWin_ = other.maxWin_;
      clientOptions_ = other.clientOptions_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespGetGameInfo Clone() {
      return new RespGetGameInfo(this);
    }

    /// <summary>Field number for the "GameID" field.</summary>
    public const int GameIDFieldNumber = 1;
    private int gameID_;
    /// <summary>
    /// 遊戲編號
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GameID {
      get { return gameID_; }
      set {
        gameID_ = value;
      }
    }

    /// <summary>Field number for the "GameCode" field.</summary>
    public const int GameCodeFieldNumber = 2;
    private string gameCode_ = "";
    /// <summary>
    /// 遊戲代碼
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GameCode {
      get { return gameCode_; }
      set {
        gameCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "GameType" field.</summary>
    public const int GameTypeFieldNumber = 3;
    private string gameType_ = "";
    /// <summary>
    /// 遊戲模式
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GameType {
      get { return gameType_; }
      set {
        gameType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "RecordUrl" field.</summary>
    public const int RecordUrlFieldNumber = 4;
    private string recordUrl_ = "";
    /// <summary>
    /// 遊戲紀錄網頁的Url
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RecordUrl {
      get { return recordUrl_; }
      set {
        recordUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "BetRange" field.</summary>
    public const int BetRangeFieldNumber = 5;
    private static readonly pb::FieldCodec<ulong> _repeated_betRange_codec
        = pb::FieldCodec.ForUInt64(42);
    private readonly pbc::RepeatedField<ulong> betRange_ = new pbc::RepeatedField<ulong>();
    /// <summary>
    /// 押注區間
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<ulong> BetRange {
      get { return betRange_; }
    }

    /// <summary>Field number for the "MaxWin" field.</summary>
    public const int MaxWinFieldNumber = 7;
    private int maxWin_;
    /// <summary>
    /// 單局最高贏分倍數
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxWin {
      get { return maxWin_; }
      set {
        maxWin_ = value;
      }
    }

    /// <summary>Field number for the "ClientOptions" field.</summary>
    public const int ClientOptionsFieldNumber = 6;
    private string clientOptions_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientOptions {
      get { return clientOptions_; }
      set {
        clientOptions_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RespGetGameInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RespGetGameInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameID != other.GameID) return false;
      if (GameCode != other.GameCode) return false;
      if (GameType != other.GameType) return false;
      if (RecordUrl != other.RecordUrl) return false;
      if(!betRange_.Equals(other.betRange_)) return false;
      if (MaxWin != other.MaxWin) return false;
      if (ClientOptions != other.ClientOptions) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GameID != 0) hash ^= GameID.GetHashCode();
      if (GameCode.Length != 0) hash ^= GameCode.GetHashCode();
      if (GameType.Length != 0) hash ^= GameType.GetHashCode();
      if (RecordUrl.Length != 0) hash ^= RecordUrl.GetHashCode();
      hash ^= betRange_.GetHashCode();
      if (MaxWin != 0) hash ^= MaxWin.GetHashCode();
      if (ClientOptions.Length != 0) hash ^= ClientOptions.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GameID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GameID);
      }
      if (GameCode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(GameCode);
      }
      if (GameType.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GameType);
      }
      if (RecordUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(RecordUrl);
      }
      betRange_.WriteTo(output, _repeated_betRange_codec);
      if (ClientOptions.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ClientOptions);
      }
      if (MaxWin != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(MaxWin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GameID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GameID);
      }
      if (GameCode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(GameCode);
      }
      if (GameType.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GameType);
      }
      if (RecordUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(RecordUrl);
      }
      betRange_.WriteTo(ref output, _repeated_betRange_codec);
      if (ClientOptions.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ClientOptions);
      }
      if (MaxWin != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(MaxWin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GameID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameID);
      }
      if (GameCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameCode);
      }
      if (GameType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameType);
      }
      if (RecordUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RecordUrl);
      }
      size += betRange_.CalculateSize(_repeated_betRange_codec);
      if (MaxWin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxWin);
      }
      if (ClientOptions.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientOptions);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RespGetGameInfo other) {
      if (other == null) {
        return;
      }
      if (other.GameID != 0) {
        GameID = other.GameID;
      }
      if (other.GameCode.Length != 0) {
        GameCode = other.GameCode;
      }
      if (other.GameType.Length != 0) {
        GameType = other.GameType;
      }
      if (other.RecordUrl.Length != 0) {
        RecordUrl = other.RecordUrl;
      }
      betRange_.Add(other.betRange_);
      if (other.MaxWin != 0) {
        MaxWin = other.MaxWin;
      }
      if (other.ClientOptions.Length != 0) {
        ClientOptions = other.ClientOptions;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GameID = input.ReadInt32();
            break;
          }
          case 18: {
            GameCode = input.ReadString();
            break;
          }
          case 26: {
            GameType = input.ReadString();
            break;
          }
          case 34: {
            RecordUrl = input.ReadString();
            break;
          }
          case 42:
          case 40: {
            betRange_.AddEntriesFrom(input, _repeated_betRange_codec);
            break;
          }
          case 50: {
            ClientOptions = input.ReadString();
            break;
          }
          case 56: {
            MaxWin = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GameID = input.ReadInt32();
            break;
          }
          case 18: {
            GameCode = input.ReadString();
            break;
          }
          case 26: {
            GameType = input.ReadString();
            break;
          }
          case 34: {
            RecordUrl = input.ReadString();
            break;
          }
          case 42:
          case 40: {
            betRange_.AddEntriesFrom(ref input, _repeated_betRange_codec);
            break;
          }
          case 50: {
            ClientOptions = input.ReadString();
            break;
          }
          case 56: {
            MaxWin = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
