// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Gateway/MemberInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.Gateway {

  /// <summary>Holder for reflection information generated from Gateway/MemberInfo.proto</summary>
  public static partial class MemberInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for Gateway/MemberInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MemberInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhHYXRld2F5L01lbWJlckluZm8ucHJvdG8SB0dhdGV3YXkiSQoGSXBJbmZv",
            "EgoKAklwGAEgASgJEg8KB0NvdW50cnkYAiABKAkSDgoGUmVnaW9uGAMgASgJ",
            "EhIKClBvc3RhbENvZGUYBCABKAki7wIKCk1lbWJlckluZm8SDgoGVXNlcklk",
            "GAEgASgDEhIKClBsYXRmb3JtSWQYAiABKAUSEgoKT3BlcmF0b3JJZBgDIAEo",
            "CRINCgVUb2tlbhgEIAEoCRIXCg9Ub2tlblVwZGF0ZVRpbWUYBSABKAMSEAoI",
            "R2FtZUNvZGUYBiABKAkSEgoKQ3JlYXRlVGltZRgHIAEoAxIRCglMb2dpblRp",
            "bWUYCCABKAMSDwoHQWNjb3VudBgJIAEoCRIQCghVc2VyQ29kZRgKIAEoCRIQ",
            "CghOaWNrbmFtZRgLIAEoCRIQCghDdXJyZW5jeRgMIAEoCRIPCgdJc0Jsb2Nr",
            "GA0gASgFEhAKCElzVGVzdGVyGA4gASgFEg4KBlN0YXR1cxgPIAEoBRItCgpQ",
            "cmVmZXJlbmNlGBAgASgLMhkuR2F0ZXdheS5NZW1iZXJQcmVmZXJlbmNlEh8K",
            "BklwSW5mbxgRIAEoCzIPLkdhdGV3YXkuSXBJbmZvIiMKEE1lbWJlclByZWZl",
            "cmVuY2USDwoHSG9tZVVybBgBIAEoCUJTWj5naXRsYWIudGhlLWZvcmNlLmNv",
            "bS50dy9zZXJ2ZXIvcHJvdG9idWYvR2VuL0dvL0dhdGV3YXk7R2F0ZXdheaoC",
            "EFByb3RvYnVmLkdhdGV3YXliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Gateway.IpInfo), global::Protobuf.Gateway.IpInfo.Parser, new[]{ "Ip", "Country", "Region", "PostalCode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Gateway.MemberInfo), global::Protobuf.Gateway.MemberInfo.Parser, new[]{ "UserId", "PlatformId", "OperatorId", "Token", "TokenUpdateTime", "GameCode", "CreateTime", "LoginTime", "Account", "UserCode", "Nickname", "Currency", "IsBlock", "IsTester", "Status", "Preference", "IpInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Gateway.MemberPreference), global::Protobuf.Gateway.MemberPreference.Parser, new[]{ "HomeUrl" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class IpInfo : pb::IMessage<IpInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IpInfo> _parser = new pb::MessageParser<IpInfo>(() => new IpInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IpInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Gateway.MemberInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IpInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IpInfo(IpInfo other) : this() {
      ip_ = other.ip_;
      country_ = other.country_;
      region_ = other.region_;
      postalCode_ = other.postalCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IpInfo Clone() {
      return new IpInfo(this);
    }

    /// <summary>Field number for the "Ip" field.</summary>
    public const int IpFieldNumber = 1;
    private string ip_ = "";
    /// <summary>
    /// 此次登入IP
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ip {
      get { return ip_; }
      set {
        ip_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Country" field.</summary>
    public const int CountryFieldNumber = 2;
    private string country_ = "";
    /// <summary>
    /// 國家
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Country {
      get { return country_; }
      set {
        country_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Region" field.</summary>
    public const int RegionFieldNumber = 3;
    private string region_ = "";
    /// <summary>
    /// 地區
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Region {
      get { return region_; }
      set {
        region_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PostalCode" field.</summary>
    public const int PostalCodeFieldNumber = 4;
    private string postalCode_ = "";
    /// <summary>
    /// 郵遞區號, 照DB填入即可
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PostalCode {
      get { return postalCode_; }
      set {
        postalCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IpInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IpInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ip != other.Ip) return false;
      if (Country != other.Country) return false;
      if (Region != other.Region) return false;
      if (PostalCode != other.PostalCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ip.Length != 0) hash ^= Ip.GetHashCode();
      if (Country.Length != 0) hash ^= Country.GetHashCode();
      if (Region.Length != 0) hash ^= Region.GetHashCode();
      if (PostalCode.Length != 0) hash ^= PostalCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ip.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ip);
      }
      if (Country.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Country);
      }
      if (Region.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Region);
      }
      if (PostalCode.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PostalCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ip.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ip);
      }
      if (Country.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Country);
      }
      if (Region.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Region);
      }
      if (PostalCode.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PostalCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ip.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ip);
      }
      if (Country.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Country);
      }
      if (Region.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Region);
      }
      if (PostalCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PostalCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IpInfo other) {
      if (other == null) {
        return;
      }
      if (other.Ip.Length != 0) {
        Ip = other.Ip;
      }
      if (other.Country.Length != 0) {
        Country = other.Country;
      }
      if (other.Region.Length != 0) {
        Region = other.Region;
      }
      if (other.PostalCode.Length != 0) {
        PostalCode = other.PostalCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Ip = input.ReadString();
            break;
          }
          case 18: {
            Country = input.ReadString();
            break;
          }
          case 26: {
            Region = input.ReadString();
            break;
          }
          case 34: {
            PostalCode = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Ip = input.ReadString();
            break;
          }
          case 18: {
            Country = input.ReadString();
            break;
          }
          case 26: {
            Region = input.ReadString();
            break;
          }
          case 34: {
            PostalCode = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MemberInfo : pb::IMessage<MemberInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MemberInfo> _parser = new pb::MessageParser<MemberInfo>(() => new MemberInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MemberInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Gateway.MemberInfoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MemberInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MemberInfo(MemberInfo other) : this() {
      userId_ = other.userId_;
      platformId_ = other.platformId_;
      operatorId_ = other.operatorId_;
      token_ = other.token_;
      tokenUpdateTime_ = other.tokenUpdateTime_;
      gameCode_ = other.gameCode_;
      createTime_ = other.createTime_;
      loginTime_ = other.loginTime_;
      account_ = other.account_;
      userCode_ = other.userCode_;
      nickname_ = other.nickname_;
      currency_ = other.currency_;
      isBlock_ = other.isBlock_;
      isTester_ = other.isTester_;
      status_ = other.status_;
      preference_ = other.preference_ != null ? other.preference_.Clone() : null;
      ipInfo_ = other.ipInfo_ != null ? other.ipInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MemberInfo Clone() {
      return new MemberInfo(this);
    }

    /// <summary>Field number for the "UserId" field.</summary>
    public const int UserIdFieldNumber = 1;
    private long userId_;
    /// <summary>
    /// 玩家帳號編號
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "PlatformId" field.</summary>
    public const int PlatformIdFieldNumber = 2;
    private int platformId_;
    /// <summary>
    /// 第三方平台編號
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PlatformId {
      get { return platformId_; }
      set {
        platformId_ = value;
      }
    }

    /// <summary>Field number for the "OperatorId" field.</summary>
    public const int OperatorIdFieldNumber = 3;
    private string operatorId_ = "";
    /// <summary>
    /// 第三方代理ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OperatorId {
      get { return operatorId_; }
      set {
        operatorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Token" field.</summary>
    public const int TokenFieldNumber = 4;
    private string token_ = "";
    /// <summary>
    /// 第三方平台登入用的 TOKEN
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TokenUpdateTime" field.</summary>
    public const int TokenUpdateTimeFieldNumber = 5;
    private long tokenUpdateTime_;
    /// <summary>
    /// TOKEN更新時間 (timestamp, use int64 or google.protobuf.Timestamp)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TokenUpdateTime {
      get { return tokenUpdateTime_; }
      set {
        tokenUpdateTime_ = value;
      }
    }

    /// <summary>Field number for the "GameCode" field.</summary>
    public const int GameCodeFieldNumber = 6;
    private string gameCode_ = "";
    /// <summary>
    /// 遊戲代碼
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GameCode {
      get { return gameCode_; }
      set {
        gameCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CreateTime" field.</summary>
    public const int CreateTimeFieldNumber = 7;
    private long createTime_;
    /// <summary>
    /// 帳號建立時間 (timestamp)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CreateTime {
      get { return createTime_; }
      set {
        createTime_ = value;
      }
    }

    /// <summary>Field number for the "LoginTime" field.</summary>
    public const int LoginTimeFieldNumber = 8;
    private long loginTime_;
    /// <summary>
    /// 帳號登入時間 (timestamp)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LoginTime {
      get { return loginTime_; }
      set {
        loginTime_ = value;
      }
    }

    /// <summary>Field number for the "Account" field.</summary>
    public const int AccountFieldNumber = 9;
    private string account_ = "";
    /// <summary>
    /// 玩家帳號
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Account {
      get { return account_; }
      set {
        account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "UserCode" field.</summary>
    public const int UserCodeFieldNumber = 10;
    private string userCode_ = "";
    /// <summary>
    /// combo第三方平台ID, 但僅做分析資料使用
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserCode {
      get { return userCode_; }
      set {
        userCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Nickname" field.</summary>
    public const int NicknameFieldNumber = 11;
    private string nickname_ = "";
    /// <summary>
    /// 帳號暱稱
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nickname {
      get { return nickname_; }
      set {
        nickname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Currency" field.</summary>
    public const int CurrencyFieldNumber = 12;
    private string currency_ = "";
    /// <summary>
    /// 此次登入幣別
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Currency {
      get { return currency_; }
      set {
        currency_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IsBlock" field.</summary>
    public const int IsBlockFieldNumber = 13;
    private int isBlock_;
    /// <summary>
    /// 上鎖旗標 0:不鎖 1:鎖定
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IsBlock {
      get { return isBlock_; }
      set {
        isBlock_ = value;
      }
    }

    /// <summary>Field number for the "IsTester" field.</summary>
    public const int IsTesterFieldNumber = 14;
    private int isTester_;
    /// <summary>
    /// 是否為測試帳號
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IsTester {
      get { return isTester_; }
      set {
        isTester_ = value;
      }
    }

    /// <summary>Field number for the "Status" field.</summary>
    public const int StatusFieldNumber = 15;
    private int status_;
    /// <summary>
    /// 玩家狀態 0:登出 1:登入 2:斷線中 3:斷線連回中 4:大廳中 5:遊戲中
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "Preference" field.</summary>
    public const int PreferenceFieldNumber = 16;
    private global::Protobuf.Gateway.MemberPreference preference_;
    /// <summary>
    /// 玩家偏好設定
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protobuf.Gateway.MemberPreference Preference {
      get { return preference_; }
      set {
        preference_ = value;
      }
    }

    /// <summary>Field number for the "IpInfo" field.</summary>
    public const int IpInfoFieldNumber = 17;
    private global::Protobuf.Gateway.IpInfo ipInfo_;
    /// <summary>
    /// 此次登入IP
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protobuf.Gateway.IpInfo IpInfo {
      get { return ipInfo_; }
      set {
        ipInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MemberInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MemberInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (PlatformId != other.PlatformId) return false;
      if (OperatorId != other.OperatorId) return false;
      if (Token != other.Token) return false;
      if (TokenUpdateTime != other.TokenUpdateTime) return false;
      if (GameCode != other.GameCode) return false;
      if (CreateTime != other.CreateTime) return false;
      if (LoginTime != other.LoginTime) return false;
      if (Account != other.Account) return false;
      if (UserCode != other.UserCode) return false;
      if (Nickname != other.Nickname) return false;
      if (Currency != other.Currency) return false;
      if (IsBlock != other.IsBlock) return false;
      if (IsTester != other.IsTester) return false;
      if (Status != other.Status) return false;
      if (!object.Equals(Preference, other.Preference)) return false;
      if (!object.Equals(IpInfo, other.IpInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId != 0L) hash ^= UserId.GetHashCode();
      if (PlatformId != 0) hash ^= PlatformId.GetHashCode();
      if (OperatorId.Length != 0) hash ^= OperatorId.GetHashCode();
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (TokenUpdateTime != 0L) hash ^= TokenUpdateTime.GetHashCode();
      if (GameCode.Length != 0) hash ^= GameCode.GetHashCode();
      if (CreateTime != 0L) hash ^= CreateTime.GetHashCode();
      if (LoginTime != 0L) hash ^= LoginTime.GetHashCode();
      if (Account.Length != 0) hash ^= Account.GetHashCode();
      if (UserCode.Length != 0) hash ^= UserCode.GetHashCode();
      if (Nickname.Length != 0) hash ^= Nickname.GetHashCode();
      if (Currency.Length != 0) hash ^= Currency.GetHashCode();
      if (IsBlock != 0) hash ^= IsBlock.GetHashCode();
      if (IsTester != 0) hash ^= IsTester.GetHashCode();
      if (Status != 0) hash ^= Status.GetHashCode();
      if (preference_ != null) hash ^= Preference.GetHashCode();
      if (ipInfo_ != null) hash ^= IpInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(UserId);
      }
      if (PlatformId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PlatformId);
      }
      if (OperatorId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OperatorId);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Token);
      }
      if (TokenUpdateTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(TokenUpdateTime);
      }
      if (GameCode.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(GameCode);
      }
      if (CreateTime != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(CreateTime);
      }
      if (LoginTime != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(LoginTime);
      }
      if (Account.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Account);
      }
      if (UserCode.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(UserCode);
      }
      if (Nickname.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Nickname);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Currency);
      }
      if (IsBlock != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(IsBlock);
      }
      if (IsTester != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(IsTester);
      }
      if (Status != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(Status);
      }
      if (preference_ != null) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(Preference);
      }
      if (ipInfo_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(IpInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(UserId);
      }
      if (PlatformId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PlatformId);
      }
      if (OperatorId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OperatorId);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Token);
      }
      if (TokenUpdateTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(TokenUpdateTime);
      }
      if (GameCode.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(GameCode);
      }
      if (CreateTime != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(CreateTime);
      }
      if (LoginTime != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(LoginTime);
      }
      if (Account.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Account);
      }
      if (UserCode.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(UserCode);
      }
      if (Nickname.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Nickname);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Currency);
      }
      if (IsBlock != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(IsBlock);
      }
      if (IsTester != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(IsTester);
      }
      if (Status != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(Status);
      }
      if (preference_ != null) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(Preference);
      }
      if (ipInfo_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(IpInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserId);
      }
      if (PlatformId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlatformId);
      }
      if (OperatorId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OperatorId);
      }
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (TokenUpdateTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TokenUpdateTime);
      }
      if (GameCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameCode);
      }
      if (CreateTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreateTime);
      }
      if (LoginTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LoginTime);
      }
      if (Account.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
      }
      if (UserCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserCode);
      }
      if (Nickname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nickname);
      }
      if (Currency.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Currency);
      }
      if (IsBlock != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsBlock);
      }
      if (IsTester != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsTester);
      }
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Status);
      }
      if (preference_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Preference);
      }
      if (ipInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(IpInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MemberInfo other) {
      if (other == null) {
        return;
      }
      if (other.UserId != 0L) {
        UserId = other.UserId;
      }
      if (other.PlatformId != 0) {
        PlatformId = other.PlatformId;
      }
      if (other.OperatorId.Length != 0) {
        OperatorId = other.OperatorId;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      if (other.TokenUpdateTime != 0L) {
        TokenUpdateTime = other.TokenUpdateTime;
      }
      if (other.GameCode.Length != 0) {
        GameCode = other.GameCode;
      }
      if (other.CreateTime != 0L) {
        CreateTime = other.CreateTime;
      }
      if (other.LoginTime != 0L) {
        LoginTime = other.LoginTime;
      }
      if (other.Account.Length != 0) {
        Account = other.Account;
      }
      if (other.UserCode.Length != 0) {
        UserCode = other.UserCode;
      }
      if (other.Nickname.Length != 0) {
        Nickname = other.Nickname;
      }
      if (other.Currency.Length != 0) {
        Currency = other.Currency;
      }
      if (other.IsBlock != 0) {
        IsBlock = other.IsBlock;
      }
      if (other.IsTester != 0) {
        IsTester = other.IsTester;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      if (other.preference_ != null) {
        if (preference_ == null) {
          Preference = new global::Protobuf.Gateway.MemberPreference();
        }
        Preference.MergeFrom(other.Preference);
      }
      if (other.ipInfo_ != null) {
        if (ipInfo_ == null) {
          IpInfo = new global::Protobuf.Gateway.IpInfo();
        }
        IpInfo.MergeFrom(other.IpInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UserId = input.ReadInt64();
            break;
          }
          case 16: {
            PlatformId = input.ReadInt32();
            break;
          }
          case 26: {
            OperatorId = input.ReadString();
            break;
          }
          case 34: {
            Token = input.ReadString();
            break;
          }
          case 40: {
            TokenUpdateTime = input.ReadInt64();
            break;
          }
          case 50: {
            GameCode = input.ReadString();
            break;
          }
          case 56: {
            CreateTime = input.ReadInt64();
            break;
          }
          case 64: {
            LoginTime = input.ReadInt64();
            break;
          }
          case 74: {
            Account = input.ReadString();
            break;
          }
          case 82: {
            UserCode = input.ReadString();
            break;
          }
          case 90: {
            Nickname = input.ReadString();
            break;
          }
          case 98: {
            Currency = input.ReadString();
            break;
          }
          case 104: {
            IsBlock = input.ReadInt32();
            break;
          }
          case 112: {
            IsTester = input.ReadInt32();
            break;
          }
          case 120: {
            Status = input.ReadInt32();
            break;
          }
          case 130: {
            if (preference_ == null) {
              Preference = new global::Protobuf.Gateway.MemberPreference();
            }
            input.ReadMessage(Preference);
            break;
          }
          case 138: {
            if (ipInfo_ == null) {
              IpInfo = new global::Protobuf.Gateway.IpInfo();
            }
            input.ReadMessage(IpInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UserId = input.ReadInt64();
            break;
          }
          case 16: {
            PlatformId = input.ReadInt32();
            break;
          }
          case 26: {
            OperatorId = input.ReadString();
            break;
          }
          case 34: {
            Token = input.ReadString();
            break;
          }
          case 40: {
            TokenUpdateTime = input.ReadInt64();
            break;
          }
          case 50: {
            GameCode = input.ReadString();
            break;
          }
          case 56: {
            CreateTime = input.ReadInt64();
            break;
          }
          case 64: {
            LoginTime = input.ReadInt64();
            break;
          }
          case 74: {
            Account = input.ReadString();
            break;
          }
          case 82: {
            UserCode = input.ReadString();
            break;
          }
          case 90: {
            Nickname = input.ReadString();
            break;
          }
          case 98: {
            Currency = input.ReadString();
            break;
          }
          case 104: {
            IsBlock = input.ReadInt32();
            break;
          }
          case 112: {
            IsTester = input.ReadInt32();
            break;
          }
          case 120: {
            Status = input.ReadInt32();
            break;
          }
          case 130: {
            if (preference_ == null) {
              Preference = new global::Protobuf.Gateway.MemberPreference();
            }
            input.ReadMessage(Preference);
            break;
          }
          case 138: {
            if (ipInfo_ == null) {
              IpInfo = new global::Protobuf.Gateway.IpInfo();
            }
            input.ReadMessage(IpInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 請根據實際需求定義 MemberPreference message
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MemberPreference : pb::IMessage<MemberPreference>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MemberPreference> _parser = new pb::MessageParser<MemberPreference>(() => new MemberPreference());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MemberPreference> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Gateway.MemberInfoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MemberPreference() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MemberPreference(MemberPreference other) : this() {
      homeUrl_ = other.homeUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MemberPreference Clone() {
      return new MemberPreference(this);
    }

    /// <summary>Field number for the "HomeUrl" field.</summary>
    public const int HomeUrlFieldNumber = 1;
    private string homeUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string HomeUrl {
      get { return homeUrl_; }
      set {
        homeUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MemberPreference);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MemberPreference other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HomeUrl != other.HomeUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HomeUrl.Length != 0) hash ^= HomeUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HomeUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(HomeUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HomeUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(HomeUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HomeUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HomeUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MemberPreference other) {
      if (other == null) {
        return;
      }
      if (other.HomeUrl.Length != 0) {
        HomeUrl = other.HomeUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            HomeUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            HomeUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
